const STORAGE_KEY = 'online-quiz-state-v1';
const APP_USERNAME = typeof process !== 'undefined' && process.env ? process.env.APP_USERNAME : '';
const APP_PASSWORD = typeof process !== 'undefined' && process.env ? process.env.APP_PASSWORD : '';
const TEACHER = { username: APP_USERNAME, password: APP_PASSWORD };
const defaultState = {
  questions: [],
  questionsPublished: false,
  quizStopped: false,
  users: [],
  results: [],
  resultFiles: [],
  studentHistory: [],
  studentSessions: {},
  drafts: {},
  currentQuizId: null,
  healthClearedAt: null,
  importedFile: null,
  studentLoginActive: false,
  config: { totalQuestions: 0, duration: 0, start: '', end: '' },
  activity: []
};
let state = loadState();
if (!state.drafts) state.drafts = {};
if (!state.studentSessions) state.studentSessions = {};
if (typeof state.quizStopped !== 'boolean') state.quizStopped = false;
if (typeof state.studentLoginActive !== 'boolean') state.studentLoginActive = false;
if (!state.importedFile) { state.users = []; saveState(); }
let session = null;
let teacherView = 'overview';
let timerId = null;
let editingQuestionId = null;
let expandedQuestionIds = new Set();
let selectedResultFileId = null;
let persistenceTimer = null;
const SESSION_KEY = 'online-quiz-window-session-v1';

function saveWindowSession() { if (session) sessionStorage.setItem(SESSION_KEY, JSON.stringify(session)); else sessionStorage.removeItem(SESSION_KEY); }
function restoreWindowSession() { try { const saved = JSON.parse(sessionStorage.getItem(SESSION_KEY) || 'null'); return saved && (saved.role === 'teacher' || saved.role === 'student') ? saved : null; } catch { return null; } }
if (!Array.isArray(state.studentHistory)) state.studentHistory = [];
if (state.results.length && !state.studentHistory.length) {
  state.studentHistory = state.results.map(result => ({ ...result, correct: result.correct ?? Math.max(0, result.attempted - result.incorrect), durationMinutes: result.durationMinutes || 0 }));
  saveState();
}

if (!Array.isArray(state.resultFiles)) state.resultFiles = [];

function loadState() {
  try { return { ...defaultState, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') }; }
  catch { return structuredClone(defaultState); }
}
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function saveTeacherDraft(form) { const values = {}; form.querySelectorAll('input, textarea, select').forEach(field => { if (!field.name) return; if (values[field.name] === undefined) values[field.name] = field.value; else values[field.name] = Array.isArray(values[field.name]) ? [...values[field.name], field.value] : [values[field.name], field.value]; }); state.drafts[teacherView] = values; saveState(); }
function restoreTeacherDrafts() { const draft = state.drafts[teacherView]; if (!draft) return; document.querySelectorAll('#question-form input, #question-form textarea, #question-form select, #config-form input, #config-form select').forEach(field => { const stored = draft[field.name]; if (stored === undefined) return; const index = [...document.querySelectorAll(`[name="${field.name}"]`)].indexOf(field); field.value = Array.isArray(stored) ? (stored[index] || '') : stored; }); }
function saveStudentSession() { if (session?.role === 'student' && !session.completed) { state.studentSessions[session.username] = { ...session }; saveState(); } }
function clearStudentSession(username) { delete state.studentSessions[username]; saveState(); }
function esc(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
function formatDate(value) { if (!value) return 'Not scheduled'; return new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }); }
function shuffleQuestions(questions, username) { const shuffled = [...questions]; let seed = [...`${state.currentQuizId || 'quiz'}:${username}`].reduce((total, character) => (total * 31 + character.charCodeAt(0)) >>> 0, 7); for (let index = shuffled.length - 1; index > 0; index--) { seed = (seed * 1664525 + 1013904223) >>> 0; const swapIndex = seed % (index + 1); [shuffled[index], shuffled[swapIndex]] = [shuffled[swapIndex], shuffled[index]]; } if (shuffled.length > 1 && shuffled.every((question, index) => question.id === questions[index].id)) [shuffled[0], shuffled[1]] = [shuffled[1], shuffled[0]]; return shuffled; }
function quizIsLocked() { return Boolean(state.questionsPublished && !state.quizStopped && (!state.config.end || Date.now() < new Date(state.config.end).getTime())); }
function quizHasEnded() { return Boolean(state.config.end && Date.now() >= new Date(state.config.end).getTime()); }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
function icon(name) { return ({ grid: '▦', question: '?', settings: '⚙', users: '♙', results: '↗', logout: '↪', plus: '+', upload: '↑', download: '↓', clock: '◷', check: '✓', pulse: '◉', book: '▤' }[name] || '•'); }
function app() { document.querySelector('#app').innerHTML = session ? (session.role === 'teacher' ? teacherApp() : (session.completed ? studentApp() : (session.started ? studentApp() : studentQuizLobby()))) : loginApp(); saveWindowSession(); restoreTeacherDrafts(); bindEvents(); }
function loginApp() {
  return `<main class="login-page"><section class="login-art"><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><div class="art-copy"><div class="eyebrow">Learning assessment / 01</div><h1>Make every answer count.</h1><p>A focused space for thoughtful quizzes, clear feedback, and better learning outcomes.</p></div><div class="art-note">SECURE ASSESSMENT PORTAL · 2026</div></section><section class="login-side"><div class="login-box"><div class="eyebrow kicker">Secure access</div><h2>Sign in to continue</h2><p class="subtle">Enter your username and password to unlock your account.</p><form id="login-form" autocomplete="off"><div class="field"><label for="username">Username</label><input id="username" name="username" autocomplete="off" placeholder="Enter your username" required /></div><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="new-password" placeholder="Enter your password" required /></div><button class="btn btn-primary login-submit">Sign in <span>→</span></button></form></div></section></main>`;
}
function teacherApp() {
  const view = teacherView;
  return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><div class="eyebrow nav-label">Workspace</div><nav class="nav">${navButton('grid', 'Overview', 'overview', view)}${navButton('question', 'Question bank', 'questions', view)}${navButton('settings', 'Quiz configuration', 'config', view)}${navButton('users', 'Student access', 'users', view)}${navButton('results', 'Results & monitoring', 'results', view)}</nav><div class="sidebar-foot">Teacher workspace<br /><span>All changes save locally</span></div></aside><main class="main"><header class="topbar"><div><div class="eyebrow kicker">Teacher workspace</div><h1>${viewTitle(view)}</h1><p class="subtle">${viewDescription(view)}</p></div><div class="user-chip"><span class="avatar">KK</span><span>Kelvin Kayuni</span><button class="btn btn-small btn-secondary" data-action="logout">Exit</button></div></header>${viewContent(view)}</main></div>`;
}
function navButton(iconName, label, target, active) { return `<button class="${target === active ? 'active' : ''}" data-view="${target}"><span class="nav-icon">${icon(iconName)}</span>${label}</button>`; }
function viewTitle(view) { return ({ overview: 'Good morning, Kelvin.', questions: 'Question bank', config: 'Quiz configuration', users: 'Student access', results: 'Results & monitoring' }[view]); }
function viewDescription(view) { return ({ overview: 'A live view of your assessment workspace.', questions: 'Build reusable questions with flexible scoring.', config: 'Set the rules, timing, and availability window.', users: 'Import and manage student login credentials.', results: 'Track participation and export completed work.' }[view]); }
function viewContent(view) { return ({ overview: overviewView, questions: questionsView, config: configView, users: usersView, results: resultsView }[view])(); }
function overviewView() {
  const online = state.users.filter(user => user.status === 'online').length;
  const average = state.results.length ? Math.round(state.results.reduce((sum, item) => sum + item.percentage, 0) / state.results.length) : 0;
  return `<section class="grid stat-grid"><div class="card stat"><span class="eyebrow">Question bank</span><span class="value">${state.questions.length}</span><span class="label">Reusable questions</span></div><div class="card stat"><span class="eyebrow">Student access</span><span class="value">${state.users.length}</span><span class="label">Registered accounts</span></div><div class="card stat"><span class="eyebrow">Live now</span><span class="value">${online}</span><span class="label"><span class="trend">● Active participants</span></span></div><div class="card stat"><span class="eyebrow">Average score</span><span class="value">${average}%</span><span class="label">Across completed quizzes</span></div></section><section class="grid two-col"><div class="card panel"><div class="panel-head"><div><h2>Quiz pulse</h2><p class="subtle">${state.config.start ? `Scheduled for ${formatDate(state.config.start)}` : 'Your next assessment at a glance'}</p></div><button class="btn btn-secondary btn-small" data-view="config">Edit setup</button></div><div class="grid" style="grid-template-columns: repeat(3, 1fr); margin: 30px 0 18px"><div><div class="eyebrow">Questions</div><strong style="display:block;font-size:25px;margin-top:9px">${state.config.totalQuestions}</strong></div><div><div class="eyebrow">Duration</div><strong style="display:block;font-size:25px;margin-top:9px">${state.config.duration}<small style="font-size:12px;color:var(--muted)"> min</small></strong></div><div><div class="eyebrow">Deadline</div><strong style="display:block;font-size:13px;margin-top:13px">${state.config.end ? new Date(state.config.end).toLocaleDateString() : 'Open'}</strong></div></div><div class="progress"><span style="width:${state.questions.length ? Math.min(100, (state.config.totalQuestions / state.questions.length) * 100) : 0}%"></span></div><p class="subtle" style="margin:9px 0 0">${state.questions.length} questions available in the bank</p></div><div class="card panel"><div class="panel-head"><div><h2>Live students</h2><p class="subtle">Presence updates as students enter the quiz.</p></div><span class="badge">${online} online</span></div>${liveStudents()}</div></section><section class="card panel" style="margin-top:17px"><div class="panel-head"><div><h2>Recent activity</h2><p class="subtle">The latest changes in your quiz workspace.</p></div><button class="btn btn-secondary btn-small" data-action="clear-activity" ${state.activity.length ? '' : 'disabled'}>Clear activity</button></div>${activityList()}</section>`;
}
function liveStudents() { const online = state.users.filter(user => user.status === 'online'); if (!online.length) return '<div class="empty">No students are currently taking the quiz.</div>'; return `<div class="activity">${online.map(user => `<div class="activity-item"><span class="activity-icon">${icon('pulse')}</span><div><strong>${esc(user.username)}</strong><br><span class="subtle">Currently answering</span></div><span class="status">Online</span></div>`).join('')}</div>`; }
function activityList() { if (!state.activity.length) return '<div class="empty">No activity recorded yet. Your workspace will appear here as students participate.</div>'; return `<div class="activity">${state.activity.slice(0, 6).map(item => `<div class="activity-item"><span class="activity-icon">${icon(item.type || 'book')}</span><div>${esc(item.text)}<br><span class="subtle">${formatDate(item.time)}</span></div><span class="activity-time">${new Date(item.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>`).join('')}</div>`; }
function questionsView() { const locked = quizIsLocked();
  return `<section class="grid two-col"><div class="card panel"><div class="panel-head"><div><h2>${editingQuestionId ? 'Edit question' : 'Create a question'}</h2><p class="subtle">Add a reusable multiple-choice question.</p></div><span class="badge">${state.questions.length} saved</span></div><form id="question-form"><input type="hidden" name="id" value="${editingQuestionId || ''}" /><div class="field"><label>Question prompt</label><textarea name="text" placeholder="Write the question students will see..." required>${editingQuestionId ? esc(state.questions.find(question => question.id === editingQuestionId)?.text || '') : ''}</textarea></div><div class="field" style="margin-top:15px"><label>Choices <span id="choice-count">(${editingQuestionId ? state.questions.find(question => question.id === editingQuestionId).choices.length : 4})</span></label><div id="choices">${choiceInputsForEditing()}</div><button type="button" class="btn btn-secondary btn-small" data-action="add-choice">+ Add choice</button></div><div class="form-grid" style="margin-top:15px"><div class="field"><label>Correct answer</label><select id="correct-answer" name="correct">${correctOptionsForEditing()}</select></div><div class="field"><label>Marks</label><input name="marks" type="number" min="1" value="${editingQuestionId ? state.questions.find(question => question.id === editingQuestionId).marks : ''}" placeholder="Enter marks" required /></div></div><div style="display:flex;gap:9px;margin-top:18px"><button class="btn btn-primary">${editingQuestionId ? 'Update question' : 'Save question'}</button>${editingQuestionId ? '<button type="button" class="btn btn-secondary" data-action="cancel-edit">Cancel</button>' : ''}</div></form></div><div class="card panel"><div class="panel-head"><div><h2>Saved questions</h2><p class="subtle">${state.questionsPublished ? 'Published questions are available to students.' : 'Questions stay private until you submit them.'}</p></div><div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end"><button class="btn btn-secondary btn-small" data-action="clear-questions" ${state.questions.length ? '' : 'disabled'}>Clear all</button><button class="btn btn-primary btn-small" data-action="publish-questions" ${state.questions.length ? '' : 'disabled'}>${state.questionsPublished ? 'Questions submitted' : 'Submit questions'}</button></div></div><div id="question-list">${questionList()}</div></div></section>`;
}
function choiceInput(index) { return `<div class="choice-row"><input name="choice" data-choice="${index}" placeholder="Choice ${String.fromCharCode(65 + index)}" required /><button type="button" data-action="remove-choice" title="Remove choice">×</button></div>`; }
function choiceInputsForEditing() { const question = editingQuestionId && state.questions.find(item => item.id === editingQuestionId); return (question ? question.choices : ['', '', '', '']).map((choice, index) => `<div class="choice-row"><input name="choice" data-choice="${index}" value="${esc(choice)}" placeholder="Choice ${String.fromCharCode(65 + index)}" required /><button type="button" data-action="remove-choice" title="Remove choice">×</button></div>`).join(''); }
function correctOptionsForEditing() { const question = editingQuestionId && state.questions.find(item => item.id === editingQuestionId); const count = question ? question.choices.length : 4; return Array.from({ length: count }, (_, index) => `<option value="${index}" ${question?.correct === index ? 'selected' : ''}>Choice ${String.fromCharCode(65 + index)}</option>`).join(''); }
function questionList() { if (!state.questions.length) return '<div class="empty">Your question bank is empty. Add a question to begin.</div>'; return state.questions.map((question, index) => `<article class="question-item"><div class="question-meta"><span class="badge">Q${String(index + 1).padStart(2, '0')}</span><span>${question.marks} marks</span></div><h3 style="margin-top:12px">${esc(question.text)}</h3><div class="question-details" id="details-${question.id}"><p class="subtle" style="margin-bottom:0">${question.choices.length} choices · Correct answer: ${String.fromCharCode(65 + question.correct)}</p>${question.choices.map((choice, choiceIndex) => `<div class="subtle">${String.fromCharCode(65 + choiceIndex)}. ${esc(choice)}</div>`).join('')}</div><div class="question-actions"><button class="btn btn-secondary btn-small" data-action="expand-question" data-id="${question.id}">Expand</button><button class="btn btn-secondary btn-small" data-action="edit-question" data-id="${question.id}">Edit</button><button class="btn btn-coral btn-small" data-action="delete-question" data-id="${question.id}">Delete</button></div></article>`).join(''); }
function configView() { const config = state.config; return `<section class="card panel" style="max-width:760px"><div class="panel-head"><div><h2>Set the assessment rules</h2><p class="subtle">Students will see these limits when they sign in.</p></div><span class="badge">${config.totalQuestions ? `${config.totalQuestions} questions` : 'Empty rules'}</span></div><form id="config-form"><div class="form-grid"><div class="field"><label>Total questions</label><input type="number" name="totalQuestions" min="1" max="${Math.max(1, state.questions.length)}" value="${config.totalQuestions || ''}" placeholder="e.g. 10" /></div><div class="field"><label>Duration (minutes)</label><input type="number" name="duration" min="1" value="${config.duration || ''}" placeholder="e.g. 30" /></div><div class="field"><label>Start date & time</label><input type="datetime-local" name="start" value="${config.start}" /></div><div class="field"><label>End date & time</label><input type="datetime-local" name="end" value="${config.end}" /></div></div><div style="display:flex;justify-content:flex-end;gap:9px;margin-top:20px"><button type="button" class="btn btn-secondary" data-action="reset-config">Reset rules</button><button class="btn btn-primary">Save configuration</button></div></form></section>`; }
function usersView() { const file = state.importedFile; const active = Boolean(file && state.studentLoginActive); return `<section class="grid two-col"><div class="card panel"><div class="panel-head"><div><h2>Import student accounts</h2><p class="subtle">Upload an .xlsx file with username/password pairs across columns.</p></div></div><label class="upload"><span class="upload-icon">${icon('upload')}</span><strong>${file ? 'Replace Excel file' : 'Choose Excel file'}</strong><span class="subtle">Columns alternate: username, password</span><input id="user-upload" type="file" accept=".xlsx,.xls,.csv" ${active ? 'disabled' : ''} /></label>${file ? `<div class="file-row"><span><strong>${esc(file.name)}</strong><br><span class="subtle">${file.count} accounts · ${formatDate(file.uploadedAt)}</span></span><button class="btn btn-coral btn-small" data-action="delete-upload" ${active ? 'disabled' : ''}>Delete file</button></div><div class="login-activation"><span><strong>Student login</strong><br><span class="subtle">${active ? 'Workbook credentials are in use.' : 'Activate this workbook to allow student login.'}</span></span><button class="btn ${active ? 'btn-primary' : 'btn-secondary'} btn-small" data-action="toggle-student-login">${active ? 'Active' : 'Inactive'}</button></div>` : ''}<div class="hint" style="margin-top:17px">${active ? 'Delete and replace are disabled while this workbook is active.' : file ? 'Activate the workbook when you are ready to allow its credentials.' : 'The first row can be a header. Upload a workbook to configure student access.'}</div></div><div class="card panel"><div class="panel-head"><div><h2>Student directory</h2><p class="subtle">${state.users.length} account${state.users.length === 1 ? '' : 's'} available</p></div></div><div class="table-wrap"><table><thead><tr><th>Username</th><th>Status</th><th>Last seen</th></tr></thead><tbody>${state.users.map(user => `<tr><td><strong>${esc(user.username)}</strong></td><td><span class="status ${user.status === 'online' ? '' : 'offline'}">${user.status === 'online' ? 'Online' : 'Offline'}</span></td><td class="subtle">${user.lastSeen ? formatDate(user.lastSeen) : '—'}</td></tr>`).join('')}</tbody></table></div></div></section>`; }
function resultsView() { const file = state.resultFiles.find(item => item.id === selectedResultFileId) || state.resultFiles[0]; if (file) selectedResultFileId = file.id; const selectedRows = file?.rows || state.results; const health = healthResults(); return `<section class="card panel"><div class="panel-head"><div><h2>Quiz result files</h2><p class="subtle">Open a stored quiz workbook here or download it for sharing.</p></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:flex-end"><button class="btn btn-secondary btn-small" data-action="clear-result-files" ${state.resultFiles.length ? '' : 'disabled'}>Clear history</button>${file ? `<button class="btn btn-coral btn-small" data-action="delete-result-file">Delete selected</button><button class="btn btn-secondary btn-small" data-action="open-result">Open in system</button><button class="btn btn-primary btn-small" data-action="download-results">${icon('download')} Download</button>` : ''}</div></div>${state.resultFiles.length ? `<div class="file-selector"><label class="eyebrow">Select quiz file</label><select id="result-file-select">${state.resultFiles.map(item => `<option value="${item.id}" ${item.id === file.id ? 'selected' : ''}>${esc(item.name)} · ${formatDate(item.createdAt)}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Student username</th><th>Attempted</th><th>Incorrect</th><th>Total marks</th><th>Percentage</th><th>Status</th></tr></thead><tbody>${selectedRows.map(result => `<tr><td><strong>${esc(result.username)}</strong></td><td>${result.attempted}</td><td>${result.incorrect}</td><td>${result.score}/${result.totalMarks}</td><td><strong>${result.percentage}%</strong></td><td><span class="badge">Completed</span></td></tr>`).join('')}</tbody></table></div>` : '<div class="empty">No quiz result files yet. Completed quizzes will be stored here automatically.</div>'}</section><section class="grid two-col" style="margin-top:17px"><div class="card panel"><div class="panel-head"><div><h2>Live monitoring</h2><p class="subtle">Active quiz sessions</p></div><span class="badge">${state.users.filter(user => user.status === 'online').length} online</span></div>${liveStudents()}</div><div class="card panel"><div class="panel-head"><div><h2>Assessment health</h2><p class="subtle">Completion overview</p></div><button class="btn btn-secondary btn-small" data-action="clear-health" ${health.length ? '' : 'disabled'}>Clear health</button></div><div style="display:flex;align-items:baseline;gap:8px;margin:16px 0 10px"><strong style="font-size:33px;letter-spacing:-.07em">${health.length}</strong><span class="subtle">completed</span></div><div class="progress"><span style="width:${state.users.length ? Math.min(100, health.length / state.users.length * 100) : 0}%"></span></div></div></section>`; }
function studentApp() { if (session.completed) return studentResult(); const availableQuestions = state.questionsPublished ? state.questions : []; const question = availableQuestions[session.index]; if (!question) return studentAccountWithoutQuiz(); const progress = ((session.index) / Math.min(state.config.totalQuestions, availableQuestions.length)) * 100; return `<main class="main"><div class="quiz-shell"><div class="quiz-top"><div><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><p class="subtle" style="margin:14px 0 0">${esc(session.username)} · Assessment in progress</p></div><div class="student-actions"><button class="btn btn-secondary btn-small" data-action="view-student-history">View quiz history</button><button class="btn btn-secondary btn-small" data-action="download-student-history" ${state.studentHistory.some(item => item.username === session.username) ? '' : 'disabled'}>Download history</button><button class="btn btn-secondary btn-small" data-action="logout">Sign out</button><div class="timer" id="timer">${formatTime(session.remaining)}</div></div></div><div class="quiz-progress"><span style="width:${progress}%"></span></div><div class="quiz-card card"><div class="eyebrow quiz-number">Question ${session.index + 1} of ${Math.min(state.config.totalQuestions, availableQuestions.length)} · ${question.marks} marks</div><h1 class="quiz-question">${esc(question.text)}</h1><div class="answers">${question.choices.map((choice, index) => `<button class="answer ${session.selected === index ? 'selected' : ''}" data-answer="${index}"><span class="answer-letter">${String.fromCharCode(65 + index)}</span>${esc(choice)}</button>`).join('')}</div>${session.feedback ? `<div class="feedback ${session.feedback.correct ? 'correct' : 'incorrect'}">${session.feedback.correct ? `Correct. +${question.marks} marks awarded.` : 'Not quite. This question scores zero marks.'}</div>` : ''}<div class="quiz-actions"><button class="btn btn-primary" data-action="submit-answer" ${session.selected === null || session.feedback ? 'disabled' : ''}>${session.index === Math.min(state.config.totalQuestions, availableQuestions.length) - 1 ? 'Finish quiz' : 'Submit answer'} →</button>${session.feedback ? `<button class="btn btn-secondary" style="margin-left:9px" data-action="next-question">${session.index === Math.min(state.config.totalQuestions, availableQuestions.length) - 1 ? 'View result' : 'Next question'} →</button>` : ''}</div></div></div></main>`; }
function studentQuizLobby() { const canStart = state.questionsPublished && !state.quizStopped && !quizHasEnded() && state.questions.length > 0; return `<main class="main"><div class="quiz-shell"><div class="quiz-top"><div><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><p class="subtle" style="margin:14px 0 0">${esc(session.username)} · Student account</p></div><div class="student-actions"><button class="btn btn-secondary btn-small" data-action="logout">Sign out</button></div></div><section class="card result-hero"><div class="eyebrow kicker">${canStart ? 'Assessment ready' : 'No active assessment'}</div><h2>${canStart ? 'Your quiz is ready to begin.' : 'Your account is ready.'}</h2><p class="subtle">${canStart ? 'When you click Start Quiz, your individual timer and question order will begin.' : 'The teacher has not made an active quiz available yet. You can return later without losing your account access.'}</p><button class="btn btn-primary" data-action="start-quiz" ${canStart ? '' : 'disabled'}>Start Quiz</button></section></div></main>`; }
function studentActivityPanel() { return '<section class="card panel student-history-panel"><div class="panel-head"><div><h2>Recent activity</h2><p class="subtle">Your recent student activity will appear here.</p></div></div><div class="empty">No recent activity recorded.</div></section>'; }
function startStudentQuiz() { if (!session || session.role !== 'student' || state.quizStopped || quizHasEnded() || !state.questionsPublished || session.quizId !== state.currentQuizId) return showToast('This quiz is not available.'); session.started = true; saveStudentSession(); app(); }
function studentAccountWithoutQuiz() { const history = state.studentHistory.filter(item => item.username === session.username); return `<main class="main"><div class="quiz-shell"><div class="quiz-top"><div><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><p class="subtle" style="margin:14px 0 0">${esc(session.username)} · Student account</p></div><div class="student-actions"><button class="btn btn-secondary btn-small" data-action="logout">Sign out</button><button class="btn btn-secondary btn-small" data-action="view-student-history">View quiz history</button><button class="btn btn-secondary btn-small" data-action="download-student-history" ${history.length ? '' : 'disabled'}>Download history</button></div></div><section class="card result-hero"><div class="eyebrow kicker">No active assessment</div><h2>Your student account is ready.</h2><p class="subtle">There is no quiz available right now. You can still review your previous quiz history below.</p><div class="assessment-actions"><button class="btn btn-coral btn-small" data-action="clear-student-result" disabled>Clear current result</button></div></section><section class="card panel student-history-panel" id="student-history-panel"><div class="panel-head"><div><h2>Quiz history</h2><p class="subtle">Your records can be viewed or downloaded, but not deleted.</p></div></div>${studentHistoryTable(history)}</section></div></main>`; }
function studentResult() { const result = session.result || state.results.find(item => item.username === session.username); return `<main class="main"><div class="quiz-shell"><div class="quiz-top"><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><button class="btn btn-secondary btn-small" data-action="logout">Sign out</button></div><section class="card result-hero"><div class="eyebrow kicker">Assessment complete</div><div class="score-big">${result ? result.percentage : 0}%</div><h2>Well done, ${esc(session.username)}.</h2><p class="subtle">Your answers have been recorded. This attempt is final and cannot be retaken.</p><div class="grid" style="grid-template-columns:repeat(3,1fr);margin:30px 0;text-align:left"><div><div class="eyebrow">Score</div><strong>${result ? result.score : 0}/${result ? result.totalMarks : 0}</strong></div><div><div class="eyebrow">Attempted</div><strong>${result ? result.attempted : 0}</strong></div><div><div class="eyebrow">Incorrect</div><strong>${result ? result.incorrect : 0}</strong></div></div></section></div></main>`; }
function studentResult() { const result = session.result || state.results.find(item => item.username === session.username); const history = state.studentHistory.filter(item => item.username === session.username); return `<main class="main"><div class="quiz-shell"><div class="quiz-top"><div class="brand"><span class="brand-mark">OQ</span><strong>ONLINE QUIZ</strong></div><div class="student-actions"><button class="btn btn-secondary btn-small" data-action="view-student-history">View quiz history</button><button class="btn btn-secondary btn-small" data-action="download-student-history" ${history.length ? '' : 'disabled'}>Download history</button><button class="btn btn-secondary btn-small" data-action="logout">Sign out</button></div></div><section class="card result-hero"><div class="eyebrow kicker">Assessment complete</div><div class="score-big">${result ? result.percentage : 0}%</div><h2>Well done, ${esc(session.username)}.</h2><p class="subtle">Your answers have been recorded. This attempt is final and cannot be retaken.</p><div class="grid" style="grid-template-columns:repeat(3,1fr);margin:30px 0;text-align:left"><div><div class="eyebrow">Score</div><strong>${result ? result.score : 0}/${result ? result.totalMarks : 0}</strong></div><div><div class="eyebrow">Attempted</div><strong>${result ? result.attempted : 0}</strong></div><div><div class="eyebrow">Incorrect</div><strong>${result ? result.incorrect : 0}</strong></div></div><div class="assessment-actions"><button class="btn btn-coral btn-small" data-action="clear-student-result" ${result ? '' : 'disabled'}>Clear current result</button></div></section><section class="card panel student-history-panel" id="student-history-panel"><div class="panel-head"><div><h2>Quiz history</h2><p class="subtle">Your records can be viewed or downloaded, but not deleted.</p></div></div>${studentHistoryTable(history)}</section></div></main>`; }
function studentHistoryTable(history) { if (!history.length) return '<div class="empty">No completed quiz history yet.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Date</th><th>Duration</th><th>Attempted</th><th>Right</th><th>Wrong</th><th>Marks scored</th></tr></thead><tbody>${history.map(item => `<tr><td>${formatDate(item.completedAt)}</td><td>${item.durationMinutes || 0} min</td><td>${item.attempted}</td><td>${item.correct ?? Math.max(0, item.attempted - item.incorrect)}</td><td>${item.incorrect}</td><td><strong>${item.score}/${item.totalMarks}</strong></td></tr>`).join('')}</tbody></table></div>`; }
function formatTime(totalSeconds) { const minutes = Math.floor(totalSeconds / 60).toString().padStart(2, '0'); const seconds = Math.max(0, totalSeconds % 60).toString().padStart(2, '0'); return `${minutes}:${seconds}`; }
function addActivity(text, type = 'book') { state.activity.unshift({ text, type, time: new Date().toISOString() }); state.activity = state.activity.slice(0, 20); saveState(); }
function healthResults() { return state.results.filter(result => !state.healthClearedAt || result.completedAt > state.healthClearedAt); }
function bindEvents() {
  if (session?.role === 'teacher' && teacherView === 'questions' && quizIsLocked()) {
    document.querySelectorAll('#question-form input, #question-form textarea, #question-form select, #question-form button, [data-action="clear-questions"], [data-action="publish-questions"], [data-action="edit-question"], [data-action="delete-question"]').forEach(control => { control.disabled = true; });
  }
  if (session?.role === 'teacher' && teacherView === 'questions' && state.questionsPublished) document.querySelector('[data-action="stop-quiz"]')?.remove();
  if (session?.role === 'teacher' && teacherView === 'questions' && state.questionsPublished) document.querySelector('[data-action="publish-questions"]')?.insertAdjacentHTML('afterend', `<button class="btn btn-coral btn-small" data-action="stop-quiz">${state.quizStopped || quizHasEnded() ? 'Quiz stopped' : 'Stop Quiz'}</button>`);
  if (!session) document.querySelector('.hint')?.remove();
  if (session?.role === 'teacher' && teacherView === 'users' && !state.importedFile) document.querySelector('.upload')?.insertAdjacentHTML('afterend', '<div class="login-activation"><span><strong>Student login</strong><br><span class="subtle">Upload a workbook before activating student access.</span></span><button class="btn btn-secondary btn-small" disabled>Inactive</button></div>');
  document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => { teacherView = button.dataset.view; app(); }));
  document.querySelectorAll('[data-action="logout"]').forEach(button => button.addEventListener('click', logout));
  const login = document.querySelector('#login-form'); if (login) login.addEventListener('submit', handleLogin);
  const questionForm = document.querySelector('#question-form'); if (questionForm) questionForm.addEventListener('submit', saveQuestion);
  document.querySelectorAll('#question-form input, #question-form textarea, #question-form select, #config-form input, #config-form select').forEach(field => field.addEventListener('input', () => saveTeacherDraft(field.form)));
  const cancelEdit = document.querySelector('[data-action="cancel-edit"]'); if (cancelEdit) cancelEdit.addEventListener('click', () => { editingQuestionId = null; app(); });
  document.querySelectorAll('[data-action="edit-question"]').forEach(button => button.addEventListener('click', () => { editingQuestionId = button.dataset.id; app(); }));
  document.querySelectorAll('[data-action="delete-question"]').forEach(button => button.addEventListener('click', () => deleteQuestion(button.dataset.id)));
  document.querySelectorAll('[data-action="expand-question"]').forEach(button => button.addEventListener('click', () => { const id = button.dataset.id; if (expandedQuestionIds.has(id)) expandedQuestionIds.delete(id); else expandedQuestionIds.add(id); const details = document.querySelector(`#details-${id}`); details.classList.toggle('expanded'); button.textContent = details.classList.contains('expanded') ? 'Collapse' : 'Expand'; }));
  const clearQuestions = document.querySelector('[data-action="clear-questions"]'); if (clearQuestions) clearQuestions.addEventListener('click', clearAllQuestions);
  const publishQuestions = document.querySelector('[data-action="publish-questions"]'); if (publishQuestions) publishQuestions.addEventListener('click', publishQuestionsForStudents);
  const stopQuiz = document.querySelector('[data-action="stop-quiz"]'); if (stopQuiz) stopQuiz.addEventListener('click', stopQuizForEveryone);
  const configForm = document.querySelector('#config-form'); if (configForm) configForm.addEventListener('submit', saveConfig);
  const resetConfig = document.querySelector('[data-action="reset-config"]'); if (resetConfig) resetConfig.addEventListener('click', resetQuizConfig);
  const upload = document.querySelector('#user-upload'); if (upload) upload.addEventListener('change', importUsers);
  const deleteUpload = document.querySelector('[data-action="delete-upload"]'); if (deleteUpload) deleteUpload.addEventListener('click', deleteUploadedFile);
  const toggleStudentLogin = document.querySelector('[data-action="toggle-student-login"]'); if (toggleStudentLogin) toggleStudentLogin.addEventListener('click', toggleStudentLoginActivation);
  const download = document.querySelector('[data-action="download-results"]'); if (download) download.addEventListener('click', downloadResults);
  const openResult = document.querySelector('[data-action="open-result"]'); if (openResult) openResult.addEventListener('click', () => showToast('The selected workbook is open in the review table below.'));
  const viewHistory = document.querySelector('[data-action="view-student-history"]'); if (viewHistory) viewHistory.addEventListener('click', () => document.querySelector('#student-history-panel')?.scrollIntoView({ behavior: 'smooth' }));
  const downloadHistory = document.querySelector('[data-action="download-student-history"]'); if (downloadHistory) downloadHistory.addEventListener('click', downloadStudentHistory);
  const clearResultButton = document.querySelector('[data-action="clear-student-result"]'); if (clearResultButton) clearResultButton.addEventListener('click', clearStudentResult);
  const deleteResultFile = document.querySelector('[data-action="delete-result-file"]'); if (deleteResultFile) deleteResultFile.addEventListener('click', deleteSelectedResultFile);
  const clearResultFiles = document.querySelector('[data-action="clear-result-files"]'); if (clearResultFiles) clearResultFiles.addEventListener('click', clearResultFileHistory);
  const clearHealth = document.querySelector('[data-action="clear-health"]'); if (clearHealth) clearHealth.addEventListener('click', clearAssessmentHealth);
  const clearActivity = document.querySelector('[data-action="clear-activity"]'); if (clearActivity) clearActivity.addEventListener('click', clearRecentActivity);
  const startQuiz = document.querySelector('[data-action="start-quiz"]'); if (startQuiz) startQuiz.addEventListener('click', startStudentQuiz);
  const resultSelect = document.querySelector('#result-file-select'); if (resultSelect) resultSelect.addEventListener('change', () => { selectedResultFileId = resultSelect.value; app(); });
  const addChoice = document.querySelector('[data-action="add-choice"]'); if (addChoice) addChoice.addEventListener('click', () => { const choices = document.querySelectorAll('[data-choice]'); const index = choices.length; if (index >= 8) return showToast('A question can have up to 8 choices.'); document.querySelector('#choices').insertAdjacentHTML('beforeend', choiceInput(index)); const row = document.querySelectorAll('.choice-row')[index]; row.querySelector('[data-action="remove-choice"]').addEventListener('click', () => { row.remove(); renumberChoices(); }); syncCorrectOptions(); updateChoiceCount(); });
  document.querySelectorAll('[data-action="remove-choice"]').forEach(button => button.addEventListener('click', () => { const choices = document.querySelectorAll('[data-choice]'); if (choices.length <= 2) return showToast('Keep at least two choices.'); button.closest('.choice-row').remove(); renumberChoices(); }));
  document.querySelectorAll('[data-answer]').forEach(button => button.addEventListener('click', () => { if (!session.feedback) { session.selected = Number(button.dataset.answer); saveStudentSession(); app(); } }));
  const submit = document.querySelector('[data-action="submit-answer"]'); if (submit) submit.addEventListener('click', submitAnswer);
  const next = document.querySelector('[data-action="next-question"]'); if (next) next.addEventListener('click', nextQuestion);
  if (session?.role === 'student' && !session.completed && session.started && document.querySelector('#timer')) startTimer();
}
function handleLogin(event) { event.preventDefault(); const form = new FormData(event.target); const username = String(form.get('username')).trim(); const password = String(form.get('password')); if (username.toLowerCase() === TEACHER.username && password === TEACHER.password) { session = { role: 'teacher', username: TEACHER.username }; teacherView = 'overview'; app(); return; } const importedUsername = state.importedFile?.usernames?.find(item => item === username); const student = state.studentLoginActive && state.importedFile && importedUsername ? state.users.find(user => user.username === importedUsername && user.password === password) : null; if (!student) return showToast('Incorrect Username or Password'); const previous = state.results.find(result => result.username === username && state.questionsPublished && state.currentQuizId && result.quizId === state.currentQuizId); if (previous) { session = { role: 'student', username: student.username, completed: true, result: previous }; app(); return; } const savedSession = state.studentSessions[student.username]; const originalQuestions = state.questions; const questionOrder = savedSession?.questionOrder?.length ? savedSession.questionOrder : shuffleQuestions(originalQuestions, username); state.questions = questionOrder; state.users = state.users.map(user => user.username === student.username ? { ...user, status: 'online', lastSeen: new Date().toISOString() } : user); session = savedSession && savedSession.quizId === state.currentQuizId ? { ...savedSession, role: 'student', originalQuestions, questionOrder } : { role: 'student', username: student.username, quizId: state.currentQuizId, originalQuestions, questionOrder, index: 0, selected: null, feedback: null, remaining: Math.max(60, state.config.duration * 60), answers: [] }; saveStudentSession(); app(); }
function logout() { stopTimer(); if (session?.role === 'student') { state.users = state.users.map(user => user.username === session.username ? { ...user, status: 'offline', lastSeen: new Date().toISOString() } : user); if (session.originalQuestions) state.questions = session.originalQuestions; saveState(); } session = null; saveWindowSession(); app(); }
function saveQuestion(event) { event.preventDefault(); if (quizIsLocked()) return showToast('Stop the quiz before changing questions.'); const data = new FormData(event.target); const choices = [...event.target.querySelectorAll('input[name="choice"]')].map(input => input.value.trim()).filter(Boolean); const correct = Math.min(Number(data.get('correct')), choices.length - 1); const id = data.get('id') || `q${Date.now()}`; const question = { id, text: data.get('text').trim(), choices, correct, marks: Number(data.get('marks')) || 1 }; const existingIndex = state.questions.findIndex(item => item.id === id); if (existingIndex >= 0) state.questions[existingIndex] = question; else state.questions.push(question); state.questionsPublished = false; state.studentSessions = {}; delete state.drafts.questions; editingQuestionId = null; saveState(); addActivity(existingIndex >= 0 ? 'A saved question was updated' : 'A new question was added', 'question'); showToast(existingIndex >= 0 ? 'Question updated. Submit questions again to publish changes.' : 'Question saved to the bank.'); app(); }
function deleteQuestion(id) { if (quizIsLocked()) return showToast('Stop the quiz before changing questions.'); state.questions = state.questions.filter(question => question.id !== id); state.questionsPublished = false; state.studentSessions = {}; saveState(); addActivity('A saved question was deleted', 'question'); showToast('Question deleted.'); app(); }
function clearAllQuestions() { if (quizIsLocked()) return showToast('Stop the quiz before changing questions.'); state.questions = []; state.questionsPublished = false; state.studentSessions = {}; saveState(); addActivity('All saved questions were cleared', 'question'); showToast('Question bank cleared.'); app(); }
function publishQuestionsForStudents() { if (quizIsLocked()) return showToast('Stop the quiz before submitting new questions.'); if (!state.questions.length) return showToast('Add at least one saved question first.'); state.questionsPublished = true; state.quizStopped = false; state.currentQuizId = `quiz-${Date.now()}`; state.studentSessions = {}; state.results = []; state.healthClearedAt = null; state.config.totalQuestions = Math.min(state.config.totalQuestions || state.questions.length, state.questions.length); saveState(); addActivity('Saved questions were submitted to students', 'check'); showToast('Questions are now accessible to students.'); app(); }
function stopQuizForEveryone() { if (!state.questionsPublished) return; state.quizStopped = true; Object.keys(state.studentSessions).forEach(username => delete state.studentSessions[username]); saveState(); addActivity('Quiz stopped for all students', 'results'); showToast('Quiz stopped. Question controls are enabled again.'); app(); }
function saveConfig(event) { event.preventDefault(); const data = new FormData(event.target); state.config = { totalQuestions: Math.min(Number(data.get('totalQuestions')) || 0, state.questions.length), duration: Number(data.get('duration')) || 0, start: data.get('start'), end: data.get('end') }; Object.values(state.studentSessions).forEach(studentSession => { if (!studentSession.started) studentSession.remaining = Math.max(60, state.config.duration * 60); }); delete state.drafts.config; saveState(); addActivity('Quiz configuration was updated', 'settings'); showToast('Quiz configuration saved.'); app(); }
function resetQuizConfig() { state.config = { totalQuestions: 0, duration: 0, start: '', end: '' }; saveState(); addActivity('Quiz configuration was reset', 'settings'); showToast('Assessment rules reset.'); app(); }
function updateChoiceCount() { const count = document.querySelectorAll('[data-choice]').length; const label = document.querySelector('#choice-count'); if (label) label.textContent = `(${count})`; }
function syncCorrectOptions() { const select = document.querySelector('#correct-answer'); if (!select) return; const selected = Number(select.value); select.innerHTML = [...document.querySelectorAll('[data-choice]')].map((input, index) => `<option value="${index}">Choice ${String.fromCharCode(65 + index)}</option>`).join(''); select.value = String(Math.min(selected, select.options.length - 1)); }
function renumberChoices() { document.querySelectorAll('[data-choice]').forEach((input, index) => { input.dataset.choice = index; input.placeholder = `Choice ${String.fromCharCode(65 + index)}`; }); document.querySelectorAll('#choices .choice-row').forEach((row, index) => row.querySelector('button').setAttribute('data-index', index)); syncCorrectOptions(); updateChoiceCount(); }
function validateCredentialRows(rows) { const credentials = []; const usernames = new Set(); const passwords = new Set(); const usernamePattern = /^(?=.*\d)[0-9A-Z./-]+$/; const passwordPattern = /^[A-Z]+$/; for (let rowIndex = 0; rowIndex < rows.length; rowIndex++) { const row = rows[rowIndex].map(value => String(value ?? '').trim()); if (!row.some(Boolean)) continue; for (let column = 0; column < row.length; column += 2) { const username = row[column] || ''; const password = row[column + 1] || ''; const usernameColumn = column + 1; const passwordColumn = column + 2; if (!username && !password) continue; if (!username) return { error: `Row ${rowIndex + 1}, column ${usernameColumn}: missing username for password in row ${rowIndex + 1}, column ${passwordColumn}.` }; if (!password) return { error: `Row ${rowIndex + 1}, column ${passwordColumn}: missing password for username in row ${rowIndex + 1}, column ${usernameColumn}.` }; if (username.toLowerCase() === 'username' && password.toLowerCase() === 'password') continue; if (!usernamePattern.test(username)) return { error: `Row ${rowIndex + 1}, column ${usernameColumn}: invalid username "${username}". Use digits with optional capital letters, -, /, or .` }; if (!passwordPattern.test(password)) return { error: `Row ${rowIndex + 1}, column ${passwordColumn}: invalid password. Passwords must contain capital letters only.` }; if (usernames.has(username)) return { error: `Row ${rowIndex + 1}, column ${usernameColumn}: duplicate username "${username}".` }; if (passwords.has(password)) return { error: `Row ${rowIndex + 1}, column ${passwordColumn}: duplicate password.` }; usernames.add(username); passwords.add(password); credentials.push({ username, password }); } } return { credentials }; }
async function importUsers(event) { const file = event.target.files[0]; if (!file || !window.XLSX || state.studentLoginActive) return; const buffer = await file.arrayBuffer(); const workbook = XLSX.read(buffer, { type: 'array' }); const rows = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { header: 1 }); const validation = validateCredentialRows(rows); if (validation.error || !validation.credentials.length) { event.target.value = ''; return showToast(validation.error || 'The workbook contains no student credentials.'); } removeImportedUsers(); const importedUsernames = []; validation.credentials.forEach(({ username, password }) => { state.users.push({ username, password, status: 'offline', lastSeen: null }); importedUsernames.push(username); }); state.importedFile = { name: file.name, count: validation.credentials.length, uploadedAt: new Date().toISOString(), usernames: importedUsernames }; state.studentLoginActive = false; saveState(); addActivity(`${validation.credentials.length} student account${validation.credentials.length === 1 ? '' : 's'} imported`, 'users'); showToast(`${validation.credentials.length} student account${validation.credentials.length === 1 ? '' : 's'} imported.`); app(); }
function removeImportedUsers() { const usernames = new Set(state.importedFile?.usernames || []); if (usernames.size) state.users = state.users.filter(user => !usernames.has(user.username)); state.importedFile = null; state.studentLoginActive = false; }
function deleteUploadedFile() { if (state.studentLoginActive) return; removeImportedUsers(); saveState(); addActivity('The uploaded student workbook was deleted', 'users'); showToast('Uploaded file removed.'); app(); }
function toggleStudentLoginActivation() { if (!state.importedFile) return; state.studentLoginActive = !state.studentLoginActive; saveState(); addActivity(`Uploaded student login ${state.studentLoginActive ? 'activated' : 'deactivated'}`, 'users'); showToast(state.studentLoginActive ? 'Uploaded credentials are now active.' : 'Uploaded credentials are inactive.'); app(); }
function deleteSelectedResultFile() { const file = state.resultFiles.find(item => item.id === selectedResultFileId) || state.resultFiles[0]; if (!file) return; state.resultFiles = state.resultFiles.filter(item => item.id !== file.id); selectedResultFileId = state.resultFiles[0]?.id || null; saveState(); addActivity(`Result file ${file.name} was deleted`, 'results'); showToast('Selected result file deleted.'); app(); }
function clearResultFileHistory() { if (!state.resultFiles.length) return; state.resultFiles = []; selectedResultFileId = null; saveState(); addActivity('All quiz result file history was cleared', 'results'); showToast('Quiz result history cleared.'); app(); }
function clearAssessmentHealth() { if (!healthResults().length) return; state.healthClearedAt = new Date().toISOString(); saveState(); addActivity('Assessment health metrics were cleared', 'results'); showToast('Assessment health cleared. Result files are still available.'); app(); }
function clearRecentActivity() { if (!state.activity.length) return; state.activity = []; saveState(); showToast('Recent activity cleared.'); app(); }
function downloadResults() { if (!window.XLSX) return; const file = state.resultFiles.find(item => item.id === selectedResultFileId) || state.resultFiles[0]; const results = file?.rows || state.results; if (!results.length) return; const rows = [['Student username', 'Number of questions attempted', 'Number answered incorrectly', 'Total marks obtained', 'Percentage score'], ...results.map(result => [result.username, result.attempted, result.incorrect, result.score, `${result.percentage}%`])]; const sheet = XLSX.utils.aoa_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, 'Results'); XLSX.writeFile(book, `${file?.name || 'online-quiz-results'}.xlsx`); showToast('Results workbook downloaded.'); }
function downloadStudentHistory() { if (!window.XLSX || !session) return; const history = state.studentHistory.filter(item => item.username === session.username); if (!history.length) return; const rows = [['Date', 'Duration (minutes)', 'Questions attempted', 'Questions right', 'Questions wrong', 'Marks scored', 'Total marks'], ...history.map(item => [formatDate(item.completedAt), item.durationMinutes, item.attempted, item.correct, item.incorrect, item.score, item.totalMarks])]; const sheet = XLSX.utils.aoa_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, 'Quiz history'); XLSX.writeFile(book, `${session.username}-quiz-history.xlsx`); showToast('Your quiz history was downloaded.'); }
function clearStudentResult() { if (!session || session.role !== 'student' || !session.result) return; state.results = state.results.filter(item => !(item.username === session.username && item.quizId === session.result.quizId)); session.result = null; session.completed = true; saveState(); showToast('Current assessment result cleared. Your quiz history remains available.'); app(); }
function startTimer() { stopTimer(); timerId = setInterval(() => { if (!session || session.role !== 'student' || session.completed) return stopTimer(); if (state.quizStopped || quizHasEnded() || session.quizId !== state.currentQuizId) { stopTimer(); app(); return; } session.remaining -= 1; saveStudentSession(); const timer = document.querySelector('#timer'); if (timer) timer.textContent = formatTime(session.remaining); if (session.remaining <= 0) { showToast('Time is up. Your quiz is being submitted.'); finishQuiz(true); } }, 1000); }
function stopTimer() { if (timerId) clearInterval(timerId); timerId = null; }
function submitAnswer() { if (state.quizStopped || quizHasEnded() || session.quizId !== state.currentQuizId) return showToast('This quiz is no longer active.'); const orderedQuestions = session.questionOrder || state.questions; const question = orderedQuestions[session.index]; session.feedback = { correct: session.selected === question.correct }; session.answers.push({ questionId: question.id, selected: session.selected, correct: session.feedback.correct }); saveStudentSession(); app(); }
function nextQuestion() { if (state.quizStopped || quizHasEnded() || session.quizId !== state.currentQuizId) return showToast('This quiz is no longer active.'); const orderedQuestions = session.questionOrder || state.questions; if (session.index >= Math.min(state.config.totalQuestions, orderedQuestions.length) - 1) return finishQuiz(false); session.index += 1; session.selected = null; session.feedback = null; saveStudentSession(); app(); }
function finishQuiz(autoSubmitted) { stopTimer(); const count = Math.min(state.config.totalQuestions, state.questions.length); const quizQuestions = state.questions.slice(0, count); const answersById = Object.fromEntries(session.answers.map(answer => [answer.questionId, answer])); let score = 0; let totalMarks = 0; let incorrect = 0; let correct = 0; quizQuestions.forEach(question => { totalMarks += question.marks; const answer = answersById[question.id]; if (answer?.correct) { score += question.marks; correct++; } if (answer && !answer.correct) incorrect++; }); const result = { username: session.username, quizId: state.currentQuizId, attempted: session.answers.length, correct, incorrect, score, totalMarks, percentage: totalMarks ? Math.round(score / totalMarks * 100) : 0, durationMinutes: Math.max(1, Math.ceil((state.config.duration * 60 - session.remaining) / 60)), completedAt: new Date().toISOString() }; state.results = [...state.results.filter(item => item.username !== session.username), result]; state.studentHistory.push(result); const fileId = `quiz-${state.currentQuizId || new Date().toISOString().slice(0, 10)}`; const existingFile = state.resultFiles.find(file => file.id === fileId); if (existingFile) existingFile.rows = [...existingFile.rows.filter(item => item.username !== result.username), result]; else state.resultFiles.unshift({ id: fileId, name: `online-quiz-results-${new Date().toISOString().slice(0, 10)}`, createdAt: new Date().toISOString(), rows: [result] }); state.users = state.users.map(user => user.username === session.username ? { ...user, status: 'offline', lastSeen: new Date().toISOString() } : user); saveState(); addActivity(`${session.username} ${autoSubmitted ? 'was auto-submitted' : 'completed the quiz'}`, 'check'); session.completed = true; session.result = result; app(); }
session = restoreWindowSession();
app();
window.addEventListener('pageshow', event => { if (event.persisted) { stopTimer(); session = null; app(); } });
window.addEventListener('storage', event => { if (event.key !== STORAGE_KEY || !event.newValue) return; state = loadState(); if (session?.role === 'student' && (state.quizStopped || session.quizId !== state.currentQuizId)) { stopTimer(); session = null; showToast('The quiz was updated by the teacher.'); } app(); });
